name: Elixir CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    name: Build and test
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: "Test"
      run: echo "${{ secrets.DISCORDTOKENPOLL }}" > TOKEN
    - name: Set up Elixir
      uses: actions/setup-elixir@v1
      with:
        elixir-version: '1.11' # Define the elixir version [required]
        otp-version: '22.3' # Define the OTP version [required]
    - name: Restore dependencies cache
      uses: actions/cache@v2
      with:
        path: deps
        key: ${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}
        restore-keys: ${{ runner.os }}-mix-
      env:
          discordtokenpoll: ${{ secrets.GITHUB_TOKEN }}   
    - name: Install dependencies
      run: |
        mix deps.get
        cat TOKEN
      env:
          discordtokenpoll: ${{ secrets.GITHUB_TOKEN }} 
    - name: Run tests
      run: mix test
      env:
          discordtokenpoll: ${{ secrets.GITHUB_TOKEN }} 
